% Experimental feature to use sigma-weighted variables for the RMS analysis
% This may help remove biases due to single plumes at the cloud top in the LES data
if settings.sigma_weighted_rmse
    LES.w_2     = LES.w_2     .* LES.sigma_2;
    LES.ww_2    = LES.ww_2    .* LES.sigma_2;
    LES.ww_res2 = LES.ww_res2 .* LES.sigma_2;
    LES.ww_sg2  = LES.ww_sg2  .* LES.sigma_2;
    LES.b_2     = LES.b_2     .* LES.sigma_2;
    LES.e_2     = LES.e_2     .* LES.sigma_2;
    LES.e_res2  = LES.e_res2  .* LES.sigma_2;
    LES.e_sg2   = LES.e_sg2   .* LES.sigma_2;
    LES.q_2     = LES.q_2     .* LES.sigma_2;
    LES.qv_2    = LES.qv_2    .* LES.sigma_2;
    LES.ql_2    = LES.ql_2    .* LES.sigma_2;

    SCM.w_2      = SCM.w_2     .* SCM.sigma2w;
    SCM.ww_res2  = SCM.ww_res2 .* SCM.sigma2w;
    SCM.ww_sg2   = SCM.ww_sg2  .* SCM.sigma2;
    SCM.b_2_est  = SCM.b_2_est .* SCM.sigma2w;
    SCM.e_2      = SCM.e_2     .* SCM.sigma2;
    SCM.e2_res   = SCM.e2_res  .* SCM.sigma2;
    SCM.e2_sg    = SCM.e2_sg   .* SCM.sigma2;
    SCM.q_2      = SCM.q_2     .* SCM.sigma2w;
    SCM.qv_2     = SCM.qv_2    .* SCM.sigma2w;
    SCM.ql_2     = SCM.ql_2    .* SCM.sigma2w;
end

% Calculate relative RMSE
rmse_sigma_2 = rmse_all_times(LES.times, LES.z, LES.sigma_2, SCM.times, SCM.zp, SCM.sigma2);
rmse_w_2     = rmse_all_times(LES.times, LES.z, LES.w_2,     SCM.times, SCM.zw, SCM.w_2);
rmse_ww_res2 = rmse_all_times(LES.times, LES.z, LES.ww_res2, SCM.times, SCM.zw, SCM.ww_res2);
rmse_ww_sg2  = rmse_all_times(LES.times, LES.z, LES.ww_sg2,  SCM.times, SCM.zp, SCM.ww_sg2);
rmse_e_2     = rmse_all_times(LES.times, LES.z, LES.e_2,     SCM.times, SCM.zp, SCM.e_2);
rmse_e_res2  = rmse_all_times(LES.times, LES.z, LES.e_res2,  SCM.times, SCM.zp, SCM.e2_res);
rmse_e_sg2   = rmse_all_times(LES.times, LES.z, LES.e_sg2,   SCM.times, SCM.zp, SCM.e2_sg);
rmse_b_2     = rmse_all_times(LES.times, LES.z, LES.b_2,     SCM.times, SCM.zw, SCM.b_2_est);
rmse_q_2     = rmse_all_times(LES.times, LES.z, LES.q_2,     SCM.times, SCM.zw, SCM.q_2);
rmse_qv_2    = rmse_all_times(LES.times, LES.z, LES.qv_2,    SCM.times, SCM.zw, SCM.qv_2);
rmse_ql_2    = rmse_all_times(LES.times, LES.z, LES.ql_2,    SCM.times, SCM.zw, SCM.ql_2);
rmse_cloud   = rmse_all_times( ...
    transpose(LES.t_cloud_fraction),      ...
    transpose(LES.z_cloud_fraction),      ...
    LES.cloud_fraction,        ...
    transpose(SCM.time_ser),        ...
    SCM.zw,                    ...
    SCM.cloud_fraction         ...
);

% Combine diagnostics
rmse_mean  = ( ...
    settings.weights.sigma_2 * rmse_sigma_2 + ...
    settings.weights.w_2     * rmse_w_2     + ...
    settings.weights.ww_res2 * rmse_ww_res2 + ...
    settings.weights.ww_sg2  * rmse_ww_sg2  + ...
    settings.weights.b_2     * rmse_b_2     + ...
    settings.weights.e_2     * rmse_e_2     + ...
    settings.weights.e_res2  * rmse_e_res2  + ...
    settings.weights.e_sg2   * rmse_e_sg2   + ...
    settings.weights.q_2     * rmse_q_2     + ...
    settings.weights.qv_2    * rmse_qv_2    + ...
    settings.weights.ql_2    * rmse_ql_2    + ...
    settings.weights.cloud   * rmse_cloud     ...
)/( ...
    settings.weights.sigma_2 + ...
    settings.weights.w_2     + ...
    settings.weights.ww_res2 + ...
    settings.weights.ww_sg2  + ...
    settings.weights.b_2     + ...
    settings.weights.e_2     + ...
    settings.weights.e_res2  + ...
    settings.weights.e_sg2   + ...
    settings.weights.q_2     + ...
    settings.weights.qv_2    + ...
    settings.weights.ql_2    + ...
    settings.weights.cloud     ...
);

disp(sprintf('RMSE of sigma_2: %0.4f (weight: %0.0f)', rmse_sigma_2, settings.weights.sigma_2));
disp(sprintf('RMSE of     w_2: %0.4f (weight: %0.0f)', rmse_w_2,     settings.weights.w_2));
disp(sprintf('RMSE of ww_res2: %0.4f (weight: %0.0f)', rmse_ww_res2, settings.weights.ww_res2));
disp(sprintf('RMSE of  ww_sg2: %0.4f (weight: %0.0f)', rmse_ww_sg2,  settings.weights.ww_sg2));
disp(sprintf('RMSE of     b_2: %0.4f (weight: %0.0f)', rmse_b_2,     settings.weights.b_2));
disp(sprintf('RMSE of     e_2: %0.4f (weight: %0.0f)', rmse_e_2,     settings.weights.e_2));
disp(sprintf('RMSE of  e_res2: %0.4f (weight: %0.0f)', rmse_e_res2,  settings.weights.e_res2));
disp(sprintf('RMSE of   e_sg2: %0.4f (weight: %0.0f)', rmse_e_sg2,   settings.weights.e_sg2));
disp(sprintf('RMSE of     q_2: %0.4f (weight: %0.0f)', rmse_q_2,     settings.weights.q_2));
disp(sprintf('RMSE of    qv_2: %0.4f (weight: %0.0f)', rmse_qv_2,    settings.weights.qv_2));
disp(sprintf('RMSE of    ql_2: %0.4f (weight: %0.0f)', rmse_ql_2,    settings.weights.ql_2));
disp(sprintf('RMSE of   cloud: %0.4f (weight: %0.0f)', rmse_cloud,   settings.weights.cloud));
disp(sprintf('RMSE mean      : %0.4f', rmse_mean));

% Write RMS error to file
fileID = fopen(fullfile(settings.folders.data_scm, 'rmse.txt'), 'w');
fprintf(fileID, '%12f', rmse_mean);
fclose(fileID);